[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
uefi = { version = "0.37.0", features = ["panic_handler", "logger"] }
uefi-bootinfo = { path = "../libs/uefi-bootinfo" }
page-table = { path = "../libs/page-table/"}
mem-info = { path = "../libs/mem-info/"}
constants = { path = "../libs/constants/"}
addr = { path = "../libs/addr/"}

